/*
 * Every runnable program from the "C and C++ Under the Hood" package (cuh63),
 * replayed through the SHIPPED assembler + interpreter and compared with the
 * output the real lcc 6.3 produced (fixtures/cuh63/*.expected, generated by
 * scripts/gen-cuh63-golden.py). Input-reading programs get fixtures/cuh63/
 * <name>.stdin. Any divergence from lcc fails by program name.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { createRunSession } from '../src/services/runner.js';

const dir = path.join(__dirname, 'fixtures', 'cuh63');
const programs = fs.readdirSync(dir).filter(f => f.endsWith('.a')).sort().map(f => {
  const name = f.slice(0, -2);
  const has = (ext) => fs.existsSync(path.join(dir, name + ext));
  const read = (ext) => fs.readFileSync(path.join(dir, name + ext), 'utf8');
  return {
    name,
    source:   read('.a'),
    expected: has('.expected') ? read('.expected') : null,
    lccError: has('.error') ? read('.error').trim() : null,
    inputs:   has('.stdin') ? read('.stdin').replace(/\n$/, '').split('\n') : [],
  };
});
const cases  = programs.filter(p => p.expected !== null);
const errors = programs.filter(p => p.lccError !== null);

function run(source, inputs) {
  const queue = [...inputs];
  return new Promise((resolve, reject) => {
    let out = '';
    const s = createRunSession(source, {
      onOutput: (t) => { out += t; },
      onInputRequest: () => s.provideInput(queue.shift() ?? ''),
      onDone: () => resolve(out),
      onError: (m) => reject(new Error(m)),
    }, { echoInput: false });   // lcc with piped stdin does not echo input
    s.start();
  });
}
const norm = (s) => s.replace(/\s+$/, '');

describe(`cuh63 textbook programs match real lcc output (${cases.length} programs)`, () => {
  it('corpus is present', () => { expect(cases.length).toBeGreaterThan(40); });
  it.each(cases)('$name', async ({ source, expected, inputs }) => {
    expect(norm(await run(source, inputs))).toBe(norm(expected));
  }, 5000);
});

describe(`programs real lcc refuses to assemble are refused too (${errors.length} programs)`, () => {
  it.each(errors)('$name (lcc: $lccError)', async ({ source }) => {
    await expect(run(source, [])).rejects.toThrow();
  }, 5000);
});
